// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEEvFvFPC42Alvsi87pzQbqOO3UCUU1-M',
    appId: '1:207822747556:web:f729d96419b95ac90cf331',
    messagingSenderId: '207822747556',
    projectId: 'echo24-6f2b1',
    authDomain: 'echo24-6f2b1.firebaseapp.com',
    storageBucket: 'echo24-6f2b1.firebasestorage.app',
    measurementId: 'G-L8YNKYNW9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7KJcv7CulHOLbtJ-wwZrTbpmDmKFU7o',
    appId: '1:207822747556:android:26c1c59e8a6c54b70cf331',
    messagingSenderId: '207822747556',
    projectId: 'echo24-6f2b1',
    storageBucket: 'echo24-6f2b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTflsiY5lYeVA2x2emMJej7bofp4ptCR8',
    appId: '1:207822747556:ios:9f6d3e5f3a26a7d10cf331',
    messagingSenderId: '207822747556',
    projectId: 'echo24-6f2b1',
    storageBucket: 'echo24-6f2b1.firebasestorage.app',
    iosBundleId: 'com.example.echo24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEEvFvFPC42Alvsi87pzQbqOO3UCUU1-M',
    appId: '1:207822747556:web:c719bf0fa0b79a700cf331',
    messagingSenderId: '207822747556',
    projectId: 'echo24-6f2b1',
    authDomain: 'echo24-6f2b1.firebaseapp.com',
    storageBucket: 'echo24-6f2b1.firebasestorage.app',
    measurementId: 'G-CWLSV0VZW9',
  );
}
